# This is a basic workflow to help you get started with Actions

name: Code Freeze

on:
  workflow_dispatch:

jobs:
  frezze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Frozono Execution
        run: |
          sudo snap install --classic kotlin && \
          chmod u+x scripts/Frozono.main.kts && \
          cd scripts/ && \
          ./Frozono.main.kts --token ${{ secrets.ADMIN_TOKEN }} --webhook ${{ secrets.SLACK_WEBHOOK }}