name: Slack notifier

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      message:
        required: true
        type: string
      color:
        required: true
        type: string
    secrets:
      webhook:
        required: true

jobs:
  notification:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: android
          SLACK_COLOR: ${{ inputs.color }}
          SLACK_MESSAGE: ${{ inputs.message }}
          SLACK_TITLE: ${{ inputs.title }}
          SLACK_USERNAME: bot
          SLACK_WEBHOOK: ${{ secrets.webhook }}
          MSG_MINIMAL: event,actions url