# Workflow to run on each PR

name: PR and branch naming rule

on:
  pull_request:
    branches: [ master ]
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  naming_rule:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_output.outputs.status }}
    steps:

      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(((feature|hotfix|fix)\/){1}(((ECCMI|eccmi|ECCMA|eccma|ECHMA|echma|ECHMD|echmd|ECE|ece|EEMD|eemd|ECCMD|eccmd|MA|ma){1}-[0-9]{1,}.{1,}))|((nonjira|NONJIRA){1}-.{1,}))|^((version|release)\/){1}(((v|V){1}[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}_.{1,}))$'
          github_token: ${{ secrets.ADMIN_TOKEN }}

      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(((feature|hotfix|fix)\/){1}(((ECCMI|eccmi|ECCMA|eccma|ECHMA|echma|ECHMD|echmd|ECE|ece|EEMD|eemd|ECCMD|eccmd|MA|ma){1}-[0-9]{1,}.{1,}))|((nonjira|NONJIRA){1}-.{1,}))|^((version|release)\/){1}(((v|V){1}[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}_.{1,}))$'
          ignore: master,develop,test,release
