name: Run unit tests

on:
  workflow_call:
    secrets:
      android_home:
        required: true
    outputs:
      status:
        value: ${{ jobs.unit_tests.outputs.status }}

jobs:
  unit_tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_output.outputs.status }}
    steps:
      - uses: actions/checkout@v2
      - name: Create local.properties
        run: |
          echo keystoreAlias=wallet >> local.properties
          echo keystorePassword=wallet >> local.properties
          echo keystorepath=wallet >> local.properties
          echo mixpanelToken=wallet >> local.properties
          echo sdk.dir=${{ secrets.android_home }} >> local.properties
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Run tests
        run: |
          ./gradlew testDebugUnitTest --no-daemon
      - name: set output
        id: set_output
        if: always()
        run: echo ::set-output name=status::${{ job.status }}